name: Security Audit

on:
  schedule:
    - cron: '0 2 * * 1'  
  workflow_dispatch:   

jobs:
  security:
    name: Security Audit Job - ${{ github.event_name == 'schedule' && 'Scheduled' || 'Manual' }} - ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy scan
        run: trivy fs --exit-code 1 --no-progress .

      - name: Upload Trivy results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-report.html

      - name: Notify Security Scan Results
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = './trivy-report.html';
            const reportExists = fs.existsSync(path);
            if (reportExists) {
              const report = fs.readFileSync(path, 'utf8');
              if (report.includes('Vulnerabilities')) {
                core.setFailed('Security vulnerabilities detected');
              } else {
                console.log('No vulnerabilities found');
              }
            } else {
              core.setFailed('No report found');
