name: Security Audit

on:
  schedule:
    - cron: '0 2 * * 1'  
  workflow_dispatch:   

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          version: 'latest'

      - name: Run Trivy scan
        run: trivy fs --exit-code 1 --no-progress .

      - name: Upload Trivy results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-report.html

      - name: Notify Security Scan Results
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = './trivy-report.html';
            const reportExists = fs.existsSync(path);
            if (reportExists) {
              const report = fs.readFileSync(path, 'utf8');
              if (report.includes('Vulnerabilities')) {
                core.setFailed('Security vulnerabilities detected');
              } else {
                console.log('No vulnerabilities found');
              }
            } else {
              core.setFailed('No report found');
            }
