name: Build and Test Job - ${{ github.event_name == 'push' && 'Push' || 'PR' }} - ${{ github.actor }}
runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v4  

  - name: Set up Node.js 20
    uses: actions/setup-node@v4  
    with:
      node-version: '20'

  - name: Install dependencies
    run: npm install

  - name: Build project
    run: npm run build

  - name: Run tests
    run: npm test

  - name: Debug - List files
    run: ls -la

  - name: Debug - Show Node.js version
    run: node -v

  - name: Debug - Show npm version
    run: npm -v
